#!/usr/bin/env bash

set -e

CONFIG=`nix eval "(import ./nix/configuration.nix).outPath"`
SEARCH_PATH=`nix eval "(import ./nix/search-path.nix)"`

CONFIG=`echo $CONFIG | cut -d'"' -f2`
SEARCH_PATH=`echo $SEARCH_PATH | cut -d'"' -f2`

nix build -f ./nix/configuration.nix

echo "Xephyr -br -ac -noreset -screen 1664x936 :1" | nix run nixpkgs.xorg.xorgserver &
echo "DISPLAY=:1 awesome -c $CONFIG/rc.lua $SEARCH_PATH" | nix run nixpkgs.awesome
