#!/usr/bin/env bash

set -e

CONFIG=`nix eval "(import ./nix/configuration.nix).outPath"`
SEARCH_PATH=`nix eval "(import ./nix/search-path.nix)"`

CONFIG=`echo $CONFIG | cut -d'"' -f2`
SEARCH_PATH=`echo $SEARCH_PATH | cut -d'"' -f2`

nix build -f ./nix/configuration.nix

Xephyr -br -ac -noreset -screen 1664x936 :20 &
DISPLAY=:20 awesome -c $CONFIG/rc.lua $SEARCH_PATH --search $CONFIG
